// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteItems(arg1:string,arg2:string):Promise<boolean>;

export function AddFavoriteTime(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function Cancel(arg1:string):Promise<boolean>;

export function DeleteFavoriteItems(arg1:string):Promise<boolean>;

export function DeleteFavoriteTime(arg1:string):Promise<boolean>;

export function Items(arg1:string,arg2:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Reservations():Promise<string>;

export function Reserve(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function Setting():Promise<string>;
