// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteItems(arg1, arg2) {
  return window['go']['main']['App']['AddFavoriteItems'](arg1, arg2);
}

export function AddFavoriteTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFavoriteTime'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function DeleteFavoriteItems(arg1) {
  return window['go']['main']['App']['DeleteFavoriteItems'](arg1);
}

export function DeleteFavoriteTime(arg1) {
  return window['go']['main']['App']['DeleteFavoriteTime'](arg1);
}

export function Items(arg1, arg2) {
  return window['go']['main']['App']['Items'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Reservations() {
  return window['go']['main']['App']['Reservations']();
}

export function Reserve(arg1, arg2, arg3) {
  return window['go']['main']['App']['Reserve'](arg1, arg2, arg3);
}

export function Setting() {
  return window['go']['main']['App']['Setting']();
}
